### ISSUE TITLE
add link to this repo on its Firefox addon's page

### ISSUE THREAD

**Issue by hugurp** [jayesh-bhoot/pin-unpin-tab#1]
Hi!

Had to go through a little bit of search to find your repo, I think people on the Firefox community would love to see that this addon is open source.

In any case, thanks a lot, this must be the addon I use the most.

Cheers

**Comment by jayesh-bhoot** [comment]
I replied through email last night (that's the the email notification from GitHub prompted me to do), but somehow it has failed to show up here.

Anyway, I am glad you find this addon useful!

You are right about linking the source to the AMO site. I will do it as soon as possible.

I also plan to add FF57+ compatibility, and the ability to customize the keyboard shortcut.

**Comment by jayesh-bhoot** [comment]
Now, the add-on page on AMO lists this repo as its support website.
