### ISSUE TITLE
Long press pin doesn't work on mastodon

### ISSUE THREAD

**Issue by vext01** [jayesh-bhoot/pin-unpin-tab#10]
Hi,

I notice that long-click pinning doesn't work on the mastodon main interface:
https://mastodon.social/web/getting-started

(Probably on other instances of mastodon too)

**Comment by jayesh-bhoot** [comment]
I superficially tested it, but the long clicks do work on that url (and only on that specific page). Could you elaborate further so that we can pin down the issue?

**Comment by jayesh-bhoot** [comment]
Accidentally clicked on `Close and comment`.

**Comment by jayesh-bhoot** [comment]
v4 should fix this issue. If not, then feel free to reopen.
