### ISSUE TITLE
Shortcut doesn't work in Firefox while GDK_BACKEND=wayland turned on

### ISSUE THREAD

**Issue by koynoyno** [jayesh-bhoot/pin-unpin-tab#12]
* OS: Antergos Sway
* Browser: FF Nightly 68.0a1 + "GDK_BACKEND=wayland" flag

Problem: Long click works, Alt+P shortcut - doesn't. If I start FF without GDK_BACKEND=wayland flag, everything works as expected.

**Comment by jayesh-bhoot** [comment]
Hey, thanks for the report! I will reproduce it on my side and investigate the issue.

**Comment by jayesh-bhoot** [comment]
Could you see whether v4 fixes this issue?

**Comment by jayesh-bhoot** [comment]
Closing the issue for now. Feel free to reopen if you still think it exists.
