### ISSUE TITLE
Keeps pinning stuff

### ISSUE THREAD

**Issue by daniel-lo** [jayesh-bhoot/pin-unpin-tab#13]
I have no idea why but this addon keeps pinning tabs without my intention.

**Comment by jayesh-bhoot** [comment]
Could you help me out with few questions here?

1. Are you aware of the long-left-click-to-pin-unpin feature of the addon? If not, then may be that is the issue. In that case, you could either embrace that behaviour or disable it in the addon preferences.

2. Does simple left-click (not long click) causes the pinning? This is a known bug. I tried to fix it in the latest addon version (3.5). So in that case could you verify the installed version is 3.5?

**Comment by daniel-lo** [comment]
Yes I am aware of long-left-click. I am not aware of long clicking on pages by accident though. I just increased to 1000 ms and will observe. Turning it off for testing is also a good idea.

Currently installed Version is 3.5.

**Comment by jayesh-bhoot** [comment]
> Currently installed Version is 3.5. The bug could be happening here too - at least that would explain things.

Yes that means I still need to fix this bug.

Meanwhile, you could disable the longclick feature. You will lose functionality of course, but also the annoyance.

**Comment by jayesh-bhoot** [comment]
v4 should fix the bug. If not, then feel free to reopen.
