### ISSUE TITLE
[Feature Request] Config options

### ISSUE THREAD

**Issue by lonix1** [jayesh-bhoot/pin-unpin-tab#15]
Would be nice to have config options (enable / disable) for:
- long-click feature
- shortcut

For example, I like using the icon. So those other features get in the way - I'd like to disable them.

**Comment by jayesh-bhoot** [comment]
You can already disable the long-click feature in the addon preferences. In fact, I may disable long-click by default in the next version. Its doesn't behave as expected in all websites.

I am not sure about keyboard shortcut though. My focus, whenever I have time for it, is to fix the buggy long-click feature. I may consider this feature after that. 

At the moment, Firefox natively allows you to modify an add-on's shortcut. So maybe configuring it to something you will never use could help?

**Comment by lonix1** [comment]
Long click: thanks I didn't realise it was possible to disable!
Shortcut: an option would be nice but you're right it's not terribly important.

What is a real pity is that the API doesn't allow for tab double-click, like it used to. That was the best way to deal with pinning.

**Comment by lonix1** [comment]
BTW when you pin a tab it jumps to the left. Do you know whether it's possible to stop that from happenning?
