### ISSUE TITLE
Alt + P cannot work because it's the default shortcut from Windows

### ISSUE THREAD

**Issue by kanlukasz** [jayesh-bhoot/pin-unpin-tab#17]
When you click `Alt` + `P` on a Windows computer in Polish, a menu will open.
This is because the letter `P` mean `Plik`, which means` File`

![obraz](https://user-images.githubusercontent.com/30685349/89167350-9b372e80-d57b-11ea-86f6-4d27e8642b35.png)

#### My env:

1. Windows: 
![obraz](https://user-images.githubusercontent.com/30685349/89167571-de919d00-d57b-11ea-9ce2-4cfeffb1b5e4.png)

2. Firefox:
![obraz](https://user-images.githubusercontent.com/30685349/89167597-e5b8ab00-d57b-11ea-8c3f-899b3217f015.png)

**Comment by jayesh-bhoot** [comment]
Yeah the default shortcut is quite insensitive to non-English users. Sorry about that. Luckily Firefox lets you modify the shortcut for *any* addon.

![Screenshot 2020-08-03 at 14 56 19](https://user-images.githubusercontent.com/1915507/89167924-b2851480-d599-11ea-91d4-e46b4735ea60.png)

Find the setting here:

![Screenshot 2020-08-03 at 14 59 16](https://user-images.githubusercontent.com/1915507/89168149-07c12600-d59a-11ea-950a-1bdde803640e.png)
