### ISSUE TITLE
drag detection

### ISSUE THREAD

**Issue by flypenguin** [jayesh-bhoot/pin-unpin-tab#3]
Love the extension. One killer thing though: I usually drag-and-drop text really often. If I do this, the tabs change from pinned to unpinned all the time, cause I seem to drag too slowly. I also don't want to increase the click wait time, cause that is annoying.

STEPS TO REPRODUCE:

* click-drag text slowly

WHAT HAPPENS:

* tab changes from pinned to unpinned or vice versa

WHAT SHOULD HAPPEN:

* extension should detect considerable mouse movement, and NOT change pinned status. that should only happen when the mouse is not moved.

Does that sound sensible?

**Comment by jayesh-bhoot** [comment]
Yes, I noticed this bug today. I am testing a simple fix currently, however, with a caveat - the add-on ignores any sort of mouse movements (mousemove event). So, long press wouldn't work if the mouse moves even a bit (which is quite likely to happen on a touchpad).

Anyway, I am updating the add-on on AMO with this fix, banking on the rationale, that fewer people would be affected by the 'even a slight movement not allowed' bug than 'tab pins unwittingly during text selection or drag-and-drop'.

I will patch another version by the end of the weekend that allows for a slight mouse movement.

Let me know if you have a better idea.

**Comment by jayesh-bhoot** [comment]
v3.1 pushed on AMO. Now, the add-on ignores mousemove event (entirely). I have created issue #4 to deal with allowing marginal mouse movement during long click/tap. Drop a comment in case you find a need to keep the current issue open.

**Comment by flypenguin** [comment]
actually sounds good to me :) . thx!

2018-02-09 13:48 GMT+01:00 Jayesh Bhoot <notifications@github.com>:
