### ISSUE TITLE
When opening a dropdown on MacOS, the tab pins/unpins

### ISSUE THREAD

**Issue by antwan** [jayesh-bhoot/pin-unpin-tab#6]
Steps to reproduce:

1. Pin tab
2. Open page with a dropdown (HTML Select)
3. Click on it: The tab gets unpinned
4. Close the dropdown.
5. Click on it: The tab gets pinned again

Reproducible: Always

**Comment by jayesh-bhoot** [comment]
I will try to find a Mac to debug this issue.

**Comment by jayesh-bhoot** [comment]
v4 should fix this issue. If not, then feel free to reopen.
