### ISSUE TITLE
How do I use this addon with a Trackpad on a Mac?

### ISSUE THREAD

**Issue by seasaltseasalt** [jayesh-bhoot/pin-unpin-tab#8]
Hello: 
1) I dont have a pin icon as shown after installing the addon.
2) I have tried what I thought was my left mouse click, long hold.. (on my trackpad) and nothing happened.  I am on a mac, sierra OSX.  Thankyou
Any chance, we could have the Tab to automatically PIN on open. So the default position is pinned?

**Comment by jayesh-bhoot** [comment]
Hello @seasaltseasalt,

I apologise for such a late response.

> 1. I dont have a pin icon as shown after installing the addon.
May be somehow the icon didn't appear on the toolbar by default. You should be able to drag-and-drop it from Firefox's Customize Page (Hamburger Menu->Customize).

> 2. I have tried what I thought was my left mouse click, long hold.. (on my trackpad) and nothing happened. I am on a mac, sierra OSX.
Have you checked whether the long click option is enabled in the add-on's preferences?

> Any chance, we could have the Tab to automatically PIN on open. So the default position is pinned?
Interesting usecase. While this seems possible, could you elaborate on your usecase further?

**Comment by jayesh-bhoot** [comment]
Closing for lack of response. Feel free to reopen.
